import os
import requests
import json
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import SystemMessage, HumanMessage
from dotenv import load_dotenv

load_dotenv()

# --- CONFIG ---
api_key = os.getenv("GOOGLE_API_KEY")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}", 
    "Accept": "application/vnd.github.v3+json"
}

# Use the model that works for you (2.5-flash)
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    google_api_key=api_key,
    temperature=0.3
)

# --- HELPER 1: FETCH CODE ---
def get_code_from_github(repo_url):
    """Fetches the main.py from the repo."""
    try:
        clean_url = repo_url.rstrip("/")
        parts = clean_url.split("/")
        owner, repo = parts[-2], parts[-1]
        
        api_url = f"https://api.github.com/repos/{owner}/{repo}/contents"
        response = requests.get(api_url, headers=HEADERS)
        
        if response.status_code != 200: return "ERROR_ACCESS", None, None

        files = response.json()
        target_file = None
        
        if isinstance(files, list):
            for f in files:
                if f["name"].endswith(".py"):
                    target_file = f
                    break
        
        if not target_file: return "NO_CODE", owner, repo

        return requests.get(target_file["download_url"]).text, owner, repo
    except Exception as e:
        return f"ERROR: {str(e)}", None, None

# --- HELPER 2: FETCH REQUIREMENTS (ISSUES) ---
def get_open_issues(owner, repo):
    """Fetches the 'Jira Tickets' (Open Issues) for the repo."""
    try:
        url = f"https://api.github.com/repos/{owner}/{repo}/issues?state=open"
        response = requests.get(url, headers=HEADERS)
        if response.status_code == 200:
            issues = response.json()
            # Extract just the titles and bodies
            summary = [f"- Ticket #{i['number']}: {i['title']}" for i in issues]
            return "\n".join(summary) if summary else "No open tickets found."
        return "Could not fetch issues."
    except:
        return "Error fetching issues."

# --- HELPER 3: POST REVIEW ---
def post_github_review(owner, repo, review_content):
    url = f"https://api.github.com/repos/{owner}/{repo}/issues"
    
    title = "⚠️ Code Review: Needs Improvement"
    if "approved" in review_content.lower() and "great" in review_content.lower():
        title = "✅ Code Review: Approved"
        
    payload = {
        "title": title,
        "body": f"## Senior Developer Feedback\n\n{review_content}\n\n---\n*Generated by Shadow Workplace AI*"
    }
    
    requests.post(url, json=payload, headers=HEADERS)

# --- MAIN NODE ---
def senior_dev_node(state):
    print("--- SENIOR DEV AGENT STARTED ---")
    repo_url = state.get("repo_url", "")
    
    if not repo_url: return {"messages": ["❌ Error: No Repo URL provided."]}

    # 1. Fetch Code
    code_result, owner, repo = get_code_from_github(repo_url)
    
    if code_result == "NO_CODE":
        return {"messages": ["⚠️ Repo is empty. Push some code first!"]}
    elif "ERROR" in code_result:
        return {"messages": [f"⚠️ Connection Error: {code_result}"]}

    # 2. Fetch Requirements (The "Sprint Plan")
    print(f"🧐 Fetching requirements for {owner}/{repo}...")
    sprint_tasks = get_open_issues(owner, repo)

    print(f"🧐 Reviewing Code vs Tickets...")

    # 3. AI Analysis (Expectation vs Reality)
    system_prompt = f"""You are a Senior Software Engineer. 
    You manage a Junior Dev who was assigned specific tickets.
    
    === THE SPRINT TASKS (EXPECTATION) ===
    {sprint_tasks}
    
    === THE CODE SUBMITTED (REALITY) ===
    {code_result}
    
    YOUR GOAL:
    Compare the Code against the Sprint Tasks.
    1. If they wrote "Hello World" but the ticket said "Build Database", SCORCH THEM.
    2. Explicitly mention which tickets they failed to implement.
    3. Be strict but professional.
    """
    
    try:
        response = llm.invoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content="Here is my PR. Review it.")
        ])
        
        review_text = response.content

        # 4. Post to GitHub
        post_github_review(owner, repo, review_text)
        
        return {"messages": [review_text]}

    except Exception as e:
        return {"messages": [f"❌ Senior Dev AI Error: {str(e)}"]}