import os
import json
import requests
import random
import string
import base64
from dotenv import load_dotenv

load_dotenv()

# --- CONFIG ---
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_API_URL = "https://api.github.com"
HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json"
}

def create_repo(repo_name):
    rand_suffix = ''.join(random.choices(string.ascii_lowercase + string.digits, k=4))
    unique_name = f"{repo_name}-{rand_suffix}"
    payload = {
        "name": unique_name,
        "description": "Shadow Workplace Simulation.",
        "private": False,
        "auto_init": True 
    }
    try:
        response = requests.post(f"{GITHUB_API_URL}/user/repos", json=payload, headers=HEADERS)
        return response.json() if response.status_code == 201 else None
    except: return None

def create_file(owner, repo, filepath, content):
    url = f"{GITHUB_API_URL}/repos/{owner}/{repo}/contents/{filepath}"
    b64_content = base64.b64encode(content.encode("utf-8")).decode("utf-8")
    payload = {"message": f"DevOps: Setup {filepath}", "content": b64_content}
    try:
        get_resp = requests.get(url, headers=HEADERS)
        if get_resp.status_code == 200: payload["sha"] = get_resp.json().get("sha")
        requests.put(url, json=payload, headers=HEADERS)
    except Exception as e: print(f"⚠️ File Error: {e}")

def create_issue(owner, repo, title, body):
    requests.post(f"{GITHUB_API_URL}/repos/{owner}/{repo}/issues", json={"title": title, "body": body}, headers=HEADERS)

def devops_node(state):
    print("--- DEVOPS AGENT STARTED ---")
    manager_output = state["messages"][-1]
    
    try:
        clean_json = manager_output.replace("```json", "").replace("```", "").strip()
        plan = json.loads(clean_json)
        
        base_name = plan.get("project_name", "shadow-project")
        tickets = plan.get("tickets", [])
        starter_files = plan.get("starter_files", []) 
        
        repo_data = create_repo(base_name)
        if not repo_data: return {"messages": ["❌ Error: Failed to create GitHub repository."]}

        full_repo_name = repo_data['name']
        owner = repo_data['owner']['login']
        repo_url = repo_data['html_url']
        
        print(f"🏗️ Repo Created: {repo_url}")
        
        # 1. Create Starter Files
        for file in starter_files:
            create_file(owner, full_repo_name, file['name'], file['content'])

        # 2. GENERATE BEAUTIFUL README
        # We use a clear, modern layout with emojis and tables/lists.
        readme_content = f"""# 🚀 Project: {base_name.replace('-', ' ').title()}

![Status](https://img.shields.io/badge/Status-Active_Simulation-success)
![Role](https://img.shields.io/badge/Role-Junior_Developer-blue)

## 📋 Mission Briefing
Welcome to the team. Your task is to implement the features listed below.
The environment has been pre-configured with the necessary starter files.

## 📂 Repository Contents
| File | Description |
|------|-------------|
"""
        if starter_files:
            for f in starter_files:
                readme_content += f"| `{f['name']}` | Pre-loaded starter code |\n"
        else:
            readme_content += "| *None* | Greenfield Project |\n"

        readme_content += """

---

## 🎟️ Your Assignment Checklist
Please complete the tickets in order.
"""
        
        # Loop through tickets and format them as clear sections
        for t in tickets:
            readme_content += f"""
### ⬜ Ticket #{t['id']}: {t['title']}
{t['body']}

<br>
"""

        readme_content += """
---

## 🚀 Submission Guide
1. **Clone** this repo.
2. **Code** the solution for each ticket.
3. **Push** to `main`.
4. **Submit** for review on your dashboard.

*Generated by Shadow Workplace AI*
"""
        
        create_file(owner, full_repo_name, "README.md", readme_content)

        # 3. Create Issues (Metadata)
        for ticket in tickets:
            create_issue(owner, full_repo_name, ticket['title'], ticket['body'])
            
        return {"messages": [f"✅ SUCCESS: Workspace ready at {repo_url}"]}
            
    except Exception as e:
        return {"messages": [f"❌ DevOps Agent Failed: {str(e)}"]}