import os
import json
import requests
import random
import string
import base64
from dotenv import load_dotenv

load_dotenv()

# --- CONFIG ---
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_API_URL = "https://api.github.com"
HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json"
}

# --- HELPER: CREATE REPO ---
def create_repo(repo_name):
    """Creates a public repository."""
    rand_suffix = ''.join(random.choices(string.ascii_lowercase + string.digits, k=4))
    unique_name = f"{repo_name}-{rand_suffix}"
    
    payload = {
        "name": unique_name,
        "description": "Shadow Workplace Simulation - Do not delete.",
        "private": False,
        "auto_init": True # Creates an empty README automatically
    }
    
    response = requests.post(f"{GITHUB_API_URL}/user/repos", json=payload, headers=HEADERS)
    
    if response.status_code == 201:
        return response.json()
    else:
        print(f"❌ GitHub Creation Failed: {response.status_code} - {response.text}")
        return None

# --- HELPER: UPDATE FILE (The Readme Writer) ---
def update_file(owner, repo, path, content, message):
    """Updates or creates a file in the repo."""
    url = f"{GITHUB_API_URL}/repos/{owner}/{repo}/contents/{path}"
    
    # 1. Get current SHA (Required to overwrite files)
    sha = None
    get_resp = requests.get(url, headers=HEADERS)
    if get_resp.status_code == 200:
        sha = get_resp.json().get("sha")

    # 2. Encode Content to Base64
    b64_content = base64.b64encode(content.encode("utf-8")).decode("utf-8")
    
    # 3. Prepare Payload
    payload = {
        "message": message,
        "content": b64_content
    }
    if sha:
        payload["sha"] = sha # Attach SHA if we are overwriting
    
    # 4. Push Update
    requests.put(url, json=payload, headers=HEADERS)

# --- HELPER: CREATE ISSUE ---
def create_issue(owner, repo, title, body):
    url = f"{GITHUB_API_URL}/repos/{owner}/{repo}/issues"
    payload = {"title": title, "body": body}
    requests.post(url, json=payload, headers=HEADERS)

# --- MAIN AGENT LOGIC ---
def devops_node(state):
    print("--- DEVOPS AGENT STARTED ---")
    
    manager_output = state["messages"][-1]
    clean_json = manager_output.replace("```json", "").replace("```", "").strip()
    
    try:
        plan = json.loads(clean_json)
        base_name = plan.get("project_name", "shadow-project")
        tickets = plan.get("tickets", [])
        
        # 1. Build the Infrastructure
        repo_data = create_repo(base_name)
        
        if repo_data:
            full_repo_name = repo_data['name']
            owner = repo_data['owner']['login']
            repo_url = repo_data['html_url']
            
            # 2. Generate the Mission Briefing (README content)
            readme_content = f"""# 🕵️ Project: {base_name.replace('_', ' ').title()}

> **Status:** Active Simulation  
> **Role:** Junior Developer

## 📋 Your Mission
You have been hired to build this module. Your manager has assigned the following tickets.
Please implement the code in `main.py` (or appropriate files) to satisfy these requirements.

## 🎟️ Active Tickets
"""
            # Add tickets to README text
            for t in tickets:
                readme_content += f"### Ticket #{t['id']}: {t['title']}\n{t['body']}\n\n"

            readme_content += """
## 🚀 How to Submit
1. Clone this repository.
2. Write your code.
3. Push your changes to `main`.
4. Go back to the **Shadow Workplace Dashboard** and click **"Submit for Review"**.

---
*Generated by Shadow Workplace AI*
"""

            # 3. Push the README to the Repo
            print(f"📝 Writing Mission Briefing to README.md...")
            update_file(owner, full_repo_name, "README.md", readme_content, "Docs: Update Mission Briefing")

            # 4. Create the Actual Jira Issues (Metadata)
            print(f"✅ Repo Created: {repo_url}")
            for ticket in tickets:
                create_issue(owner, full_repo_name, ticket['title'], ticket['body'])
                print(f"   - Created Issue: {ticket['title']}")
                
            return {"messages": [f"✅ SUCCESS: Created {repo_url} with a detailed README mission brief."]}
        else:
            return {"messages": ["❌ Failed to create GitHub repo."]}
            
    except Exception as e:
        return {"messages": [f"❌ DevOps Crash: {str(e)}"]}